# yamllint disable-line rule:line-length

dist: bionic

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
          - pkg-config
    env:
      - MY_ENVIRONMENT="CC=gcc CXX=g++-7"
      - CODECOV_TOKEN="83bcf4c4-761f-4235-9b11-023a8be02d42"

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/2.1.1/bazel_2.1.1-linux-x86_64.deb
  - sudo dpkg -i bazel_2.1.1-linux-x86_64.deb

script:
  - bazel build //...
  - bazel test //...
  - bazel coverage --combined_report=lcov //...
  - genhtml bazel-out/_coverage/_coverage_report.dat --output-directory coverage
  - ./build_for_avr.sh
