# yamllint disable-line rule:line-length

dist: bionic

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
          - lcov
          - pkg-config
    env:
      - MY_ENVIRONMENT="CC=gcc CXX=g++-7"
      - CODECOV_TOKEN="a7d6b39a-5cc2-492c-accd-2095a4e9d091"

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/2.1.1/bazel_2.1.1-linux-x86_64.deb
  - sudo dpkg -i bazel_2.1.1-linux-x86_64.deb

script:
  - bazel build --profile=/tmp/build_profile //...
  - bazel test --profile=/tmp/test_profile //...
  - bazel coverage --combined_report=lcov //...
  - genhtml bazel-out/_coverage/_coverage_report.dat --output-directory coverage
  - ./scripts/push_test_coverage.sh
