@startuml
skinparam monochrome true

    actor User
    User -> "Session::Transmit()/Receive()" : username & password

    "Session::Transmit()/Receive()"-> "Session::Login()" : username & password
    activate "Session::Login()"
    "Session::Login()" -> "Session::Transmit()/Receive()" : LoginStatus::Success
    "Session::Transmit()/Receive()" -> User : "ACK session_cookie"

    User -> "Session::Transmit()/Receive()" : "Logout"
    "Session::Transmit()/Receive()" -> "Session::Logout()"
    "Session::Logout()" -> "Session::Login()": reset cookie
    deactivate "Session::Login()"
@enduml